WebCafe/Areas/Admin/Controllers/AdminNewsController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebCafe.Models;
using Microsoft.AspNetCore.Hosting;
namespace WebCafe.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminNewsController : Controller
    {
        private readonly CuaHangBanCafeContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AdminNewsController(CuaHangBanCafeContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }


        public async Task<IActionResult> Index()
        {
            return View(await _context.TinTucs.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinTuc = await _context.TinTucs
                .FirstOrDefaultAsync(m => m.MaTt == id);
            if (tinTuc == null)
            {
                return NotFound();
            }

            return View(tinTuc);
        }


        public IActionResult Create()
        {
            ViewBag.ThongBao = "";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaTt,TenTt,AnhTt,Motangan,Motadai,Tacgia,CreateDate,LoaiTin")] TinTuc tinTuc, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (!TinTucExists(tinTuc.TenTt))
                {
                    tinTuc.CreateDate = DateTime.Now;
                    // Check if a file is selected
                    if (file != null && file.Length > 0)
                    {
                        // Get the filename and extension
                        var fileName = Path.GetFileName(file.FileName);
                        var fileExt = Path.GetExtension(fileName);

                        // Generate a unique filename
                        var uniqueFileName = Guid.NewGuid().ToString() + fileExt;

                        // Combine the path to save the file
                        var filePath = Path.Combine(_webHostEnvironment.WebRootPath, "img/tintuc", uniqueFileName);

                        // Copy the file to the path
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await file.CopyToAsync(stream);
                        }

                        // Save the filename to the model
                        tinTuc.AnhTt = uniqueFileName;
                    }

                    _context.Add(tinTuc);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                // Đưa ra thông báo
                ViewBag.ThongBao = "Tiêu đề tin tức đã tồn tại, thêm tin tức mới không thành công";
            }
            return View(tinTuc);
        }



        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                await Console.Out.WriteLineAsync("id null");
                return NotFound();
            }

            var tinTuc = await _context.TinTucs.FindAsync(id);
            if (tinTuc == null)
            {
                await Console.Out.WriteLineAsync("not found");
                return NotFound();
            }
            ViewBag.ThongBao = "";
            return View(tinTuc);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaTt,TenTt,AnhTt,Motangan,Motadai,Tacgia,CreateDate,LoaiTin")] TinTuc tinTuc)
        {
            if (id != tinTuc.MaTt)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                // Kiểm tra tin tức đã tồn tại trước đó chưa
                if (!TinTucExists(tinTuc.TenTt))
                {
                    _context.Update(tinTuc);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                // Đưa ra thông báo
                ViewBag.ThongBao = "Tiêu đề tin tức đã tồn tại, sửa tin tức không thành công";
            }
            return View(tinTuc);
        }



        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinTuc = await _context.TinTucs
                .FirstOrDefaultAsync(m => m.MaTt == id);
            if (tinTuc == null)
            {
                return NotFound();
            }

            return View(tinTuc);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var tinTuc = await _context.TinTucs.FindAsync(id);
            if (tinTuc == null)
                return View(id);
            _context.TinTucs.Remove(tinTuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TinTucExists(string TieuDe)
        {
            return _context.TinTucs.Any(e => e.TenTt == TieuDe);
        }
    }
}

WebCafe/Areas/Admin/Views/AdminNews/Create.cshtml
@model WebCafe.Models.TinTuc

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
</head>
<div class="card-body" style="margin-top:40px;background-color: var(--bs-body-bg); border-radius:12px; padding:20px;">
    <form asp-action="Create" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <a asp-action="Index" style="font-size:30px;"><i class='bx bx-arrow-back'></i></a>
        <h5 class="text-uppercase">Thêm Tin Mới</h5>

        <div class="row">

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="TenTt" class="control-label">Tiêu đề tin tức</label>
                    <input asp-for="TenTt" class="form-control" />
                    <span asp-validation-for="TenTt" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Tacgia" class="control-label">Tên tác giả</label>
                    <input asp-for="Tacgia" class="form-control" /> <br />
                    <span asp-validation-for="Tacgia" class="text-danger"></span>

                </div>
            </div>

            @*<div class="col-md-6">
                <div class="form-group">
                    <label asp-for="AnhTt" class="control-label">Link Ảnh (Video) Tin Tức</label>
                    <input asp-for="AnhTt" class="form-control" id="file-name" />
                    <span asp-validation-for="AnhTt" class="text-danger"></span>

                    <input type="button" id="choose-file" value="Choose File" class="form-control btn btn-primary col-md-6" style="margin-top:3px;" />
                </div>
            </div>*@
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="AnhTt" class="control-label">Link Ảnh (Video) Tin Tức</label>
                    <br />
                    <input type="file" id="image-file" name="file" accept=".jpg,.png" onchange="updateFileName()" />
                    <br /><br />
                    <input asp-for="AnhTt" class="form-control" id="file-name" readonly="readonly" />
                    <span asp-validation-for="AnhTt" class="text-danger"></span>
                    <br /><br />
                    <input type="button" id="choose-file" value="Choose File" class="btn btn-primary" style="margin-top:3px;" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Motangan" class="control-label">Mô Tả Ngắn</label>
                    <textarea asp-for="Motangan" class="form-control"> </textarea>
                    <span asp-validation-for="Motangan" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input type="checkbox" class="form-check-input" asp-for="LoaiTin" /> Đây là loại tin có Video
                    </label>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Motadai" class="control-label">Mô Tả Chi Tiết Tin Tức</label>
                    <textarea id="nhap-tintuc" asp-for="Motadai" class="form-control"> </textarea>
                    <span asp-validation-for="Motadai" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
                <div id="thongBao" data-tbao="@ViewBag.ThongBao"></div>
                <script src="~/js/Alert_Them_Sua_Xoa_ThatBai.js"></script>
            </div>

        </div>
    </form>
</div>

<script>
    var simplemde = new SimpleMDE({ element: document.getElementById("nhap-tintuc") });
</script>

<script>
    //var chooseFileButton = document.getElementById('choose-file');
    //var fileNameTextbox = document.getElementById('file-name');

    //chooseFileButton.addEventListener('click', function () {
    //    var fileChooser = document.createElement('input');
    //    fileChooser.setAttribute('type', 'file');
    //    fileChooser.setAttribute('accept', '.jpg,.png');

    //    fileChooser.addEventListener('change', function () {
    //        fileNameTextbox.value = fileChooser.files[0].name;
    //    });

    //    fileChooser.click('OK');
    //});

    var chooseFileButton = document.getElementById('choose-file');

    chooseFileButton.addEventListener('click', function () {
        var fileChooser = document.querySelector('#image-file');
        fileChooser.click();
    });

    function updateFileName() {
        var fileNameTextbox = document.getElementById('file-name');
        var fileChooser = document.querySelector('#image-file');

        if (fileChooser.value.length > 0) {
            fileNameTextbox.value = fileChooser.files[0].name;
        }
    }
</script>

WebCafe/Areas/Admin/Views/AdminNews/Delete.cshtml
@model WebCafe.Models.TinTuc

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<style>
    .col-sm-10,
    .col-sm-2 {
        margin-top: 10px;
        font-size: 14px;
    }

    .col-sm-2 {
        color: #000;
    }
</style>

<div style="margin-top:40px;background-color: var(--bs-body-bg); border-radius:12px; padding:20px;">
    <a asp-action="Index" style="font-size:30px;"><i class='bx bx-arrow-back'></i></a>
    <h3>Xóa Tin Tức</h3>

    <h5>Bạn có chắn muốn xóa tin này?</h5>
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2 anh-sp">
                Ảnh Tin Tức:
            </dt>
            <dd class="col-sm-10">
                <img src="@Url.Content("~/img/tintuc/" + Model.AnhTt)" style="width:200px; object-fit:cover;">
            </dd>
            <dt class="col-sm-2">
                Tiêu Đề:
            </dt>
            <dd class="col-sm-10">
                @Model.TenTt
            </dd>
            <dt class="col-sm-2">
                Tên Tác Giả:
            </dt>
            <dd class="col-sm-10">
                @Model.Tacgia
            </dd>
            <dt class="col-sm-2">
                Ngày Đăng:
            </dt>
            <dd class="col-sm-10">
                @Model.CreateDate.ToString("dd/MM/yyyy")
            </dd>
            <dt class="col-sm-2">
                Đây là tin Video:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LoaiTin)
            </dd>
            <dt class="col-sm-2">
                Mô Tả Ngắn:
            </dt>
            <dd class="col-sm-10">
                @Model.Motangan
            </dd>
            <dt class="col-sm-2">
                Mô Tả Chi Tiết:
            </dt>
            <dd class="col-sm-10">
                @Model.Motadai
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="MaTt" />
            <input type="submit" value="Xóa" class="btn btn-danger" />
        </form>
    </div>
</div>

WebCafe/Areas/Admin/Views/AdminNews/Details.cshtml
@model WebCafe.Models.TinTuc

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .col-sm-10,
    .col-sm-2 {
        margin-top: 10px;
        font-size: 14px;
    }

    .col-sm-2 {
        color: #000;
    }
</style>

<div style="margin-top:40px;background-color: var(--bs-body-bg); border-radius:12px; padding:20px;">
    <a asp-action="Index" style="font-size:30px;"><i class='bx bx-arrow-back'></i></a>
    <h1>Chi Tiết Tin Tức</h1>

    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2 anh-sp">
                Ảnh Sản Phẩm:
            </dt>
            <dd class="col-sm-10">
                <img src="@Url.Content("~/img/tintuc/"+ Model.AnhTt)" style="width:200px; object-fit:cover;">
            </dd>
            <dt class="col-sm-2">
                Tiêu Đề:
            </dt>
            <dd class="col-sm-10">
                @Model.TenTt
            </dd>
            <dt class="col-sm-2">
                Tên Tác Giả:
            </dt>
            <dd class="col-sm-10">
                @Model.Tacgia
            </dd>
            <dt class="col-sm-2">
                Ngày Đăng:
            </dt>
            <dd class="col-sm-10">
                @Model.CreateDate.ToString("dd/MM/yyyy")
            </dd>
            <dt class="col-sm-2">
                Đây là tin Video:
            </dt>
            <dd class="col-sm-10">
                @Model.LoaiTin
                @*@Html.DisplayFor(model => model.LoaiTin)*@
            </dd>
            <dt class="col-sm-2">
                Mô Tả Ngắn:
            </dt>
            <dd class="col-sm-10">
                @Model.Motangan
            </dd>
            <dt class="col-sm-2">
                Mô Tả Chi Tiết:
            </dt>
            <dd class="col-sm-10">
                @Model.Motadai
            </dd>
        </dl>
    </div>
    <div>
        <a asp-area="Admin" asp-controller="AdminNews" asp-action="Edit" asp-route-id="@Model.MaTt" class="btn btn-primary" style="font-size:12px;">Sửa</a>
        <a asp-action="Delete" asp-route-id="@Model.MaTt" class="btn btn-danger" style="font-size:12px;">Xóa</a>
    </div>
</div>

WebCafe/Areas/Admin/Views/AdminNews/Edit.cshtml
@model WebCafe.Models.TinTuc

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
</head>
<div class="card-body" style="margin-top:40px;background-color: var(--bs-body-bg); border-radius:12px; padding:20px;">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="MaTt" />
        <a asp-action="Index" style="font-size:30px;"><i class='bx bx-arrow-back'></i></a>
        <h5 class="text-uppercase">Sửa tin tức</h5>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="TenTt" class="control-label">Tiêu đề tin tức</label>
                    <input asp-for="TenTt" class="form-control" />
                    <span asp-validation-for="TenTt" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Tacgia" class="control-label">Tên tác giả</label>
                    <input asp-for="Tacgia" class="form-control" /> <br />
                    <span asp-validation-for="Tacgia" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="CreateDate" class="control-label">Ngày Tạo</label>
                    <input asp-for="CreateDate" class="form-control" />
                    <span asp-validation-for="CreateDate" class="text-danger"></span>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="LoaiTin" /> Đây là loại tin có Video
                    </label>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="AnhTt" class="control-label">Link Ảnh (Video) Tin Tức</label>
                    <input asp-for="AnhTt" class="form-control" id="file-name" />
                    <input type="button" id="choose-file" value="Choose File" class="form-control btn btn-primary col-md-3" />
                    <span asp-validation-for="AnhTt" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Motangan" class="control-label">Mô Tả Ngắn</label>
                    <textarea asp-for="Motangan" class="form-control"> </textarea>
                    <span asp-validation-for="Motangan" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Motadai" class="control-label">Mô Tả Chi Tiết Tin Tức</label>
                    <textarea id="nhap-tintuc" asp-for="Motadai" class="form-control"> </textarea>
                    <span asp-validation-for="Motadai" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
                <div id="thongBao" data-tbao="@ViewBag.ThongBao"></div>
                <script src="~/js/Alert_Them_Sua_Xoa_ThatBai.js"></script>
            </div>
        </div>
    </form>
</div>

<script>
    // js xử lý text editor
    var simplemde = new SimpleMDE({ element: document.getElementById("nhap-tintuc") });
</script>

<script>
    // Chọn ảnh
    var chooseFileButton = document.getElementById('choose-file');
    var fileNameTextbox = document.getElementById('file-name');

    chooseFileButton.addEventListener('click', function () {
        var fileChooser = document.createElement('input');
        fileChooser.setAttribute('type', 'file');
        fileChooser.setAttribute('accept', '.jpg,.png');

        fileChooser.addEventListener('change', function () {
            fileNameTextbox.value = fileChooser.files[0].name;
        });

        fileChooser.click('OK');
    });
</script>

WebCafe/Areas/Admin/Views/AdminNews/Index.cshtml
@model IEnumerable<WebCafe.Models.TinTuc>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">

</head>

<div class="col-12">
    <div class="card mb-4">
        <div class="card-header pb-0">
            <h4>Quản Lý Tin Tức</h4>
            <p>
                <a asp-action="Create" class="btn btn-primary" style="margin-top:20px;">Thêm Bài Viết</a>
            </p>
        </div>

        <div class="card-body px-0 pt-0 pb-2">
            <div class="table-responsive p-0">
                <table id="example" class="table align-items-center justify-content-center mb-0 table-striped" style="font-size:20px;">
                    <thead>
                        <tr>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder ">Tin Tức</th>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder ">Tác Giả</th>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder  ps-2">Ngày Tạo</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="d-flex px-2">
                                        <div>
                                            <img src="@Url.Content("~/img/tintuc/" + @item.AnhTt)" class="avatar avatar-sm me-2">
                                        </div>
                                        <div class="my-auto">
                                            <h6 class="mb-0 text-sm font-weight-bold" style="font-size:12px;">@item.TenTt</h6>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <span class="font-weight-bold" style="font-size:12px;">@item.Tacgia</span>
                                </td>
                                <td>
                                    <span class="font-weight-bold" style="font-size:12px;">@item.CreateDate.ToString("dd/MM/yyyy")</span>
                                </td>
                                <td class="align-middle">

                                    <a asp-action="Details" asp-route-id="@item.MaTt" class="btn btn-primary" style="font-size:12px;">Xem</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
<script src="~/js/datatables-bt5.js"></script>